// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DragAssignmentWeekController from "./drag_assignment_week_controller"
application.register("drag-assignment-week", DragAssignmentWeekController)

import EngagementAssignmentController from "./engagement_assignment_controller"
application.register("engagement-assignment", EngagementAssignmentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToggleEngagementController from "./toggle_engagement_controller"
application.register("toggle-engagement", ToggleEngagementController)

import ToggleEngagementsController from "./toggle_engagements_controller"
application.register("toggle-engagements", ToggleEngagementsController)
